version: "3.3"
services:

  exporter:
    restart: always
    container_name: tempexporter
    image: lukasbahr/raspbi-temperature-exporter:arm32v6
    environment:
      - EXPORTER_PORT=9102
    expose: 
      - 9102
    networks:
      - pi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks: 
  pi: 
    external: true