version: "3.3"
services:

  tempexporter:
    restart: always
    image: tempexporter:1.0
    environment:
    - TEMPEXPORTER_PORT=9102
    ports:
    - 9102
    networks:
      - pi

networks: 
  pi: 
    external: true